### ISSUE TITLE
Question 

### ISSUE THREAD

**Issue by dead8309** [re-ovo/md3compat#1]
The color schemes would only work with compose applications or can also work with normal XML applications too ?

**Comment by re-ovo** [comment]
> The color schemes would only work with compose applications or can also work with normal XML applications too ?

Hi, this library is only designed for the compose program. If you want to apply it to xml, you can make a library based on the official color picking algorithm: https://github.com/material-foundation/material-color-utilities

**Comment by dead8309** [comment]
Thanks for info!
